[toolchain]
package_manager = "yarn"
anchor_version = "0.32.1"
solana_version = "3.0.13"

[features]
resolution = true
skip-lint = false

[programs.localnet]
kernel_token = "5QVVrCBUgqjG3pWcSmRkqaagFaokaAwgoFFDLXBJgFJw"

[programs.devnet]
kernel_token = "5QVVrCBUgqjG3pWcSmRkqaagFaokaAwgoFFDLXBJgFJw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
